server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/ewm
    password: pwd
    username: ewm

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

logging:
  level:
    ru:
      practicum:
        ewmmain: trace

statistics:
  server:
    url: http://localhost:9090