server:
  port: ${MAIN_SERVER_PORT}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    password: ${DB_PASSWORD}
    username: ${DB_USER}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

logging:
  level:
    ru:
      practicum:
        ewmmain: trace

statistics:
  server:
    url: http://${STATS_SERVER_HOST}:${STATS_SERVER_PORT}