--DROP TABLE IF EXISTS users, events, locations, categories, compilations, participation_requests CASCADE;

CREATE TABLE IF NOT EXISTS categories
(
    category_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(50) UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned         boolean     NOT NULL,
    title          varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS locations
(
    location_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    latitude    real NOT NULL,
    longitude   real NOT NULL
);

CREATE TABLE IF NOT EXISTS users
(
    user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email   varchar(50) UNIQUE NOT NULL,
    name    varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    event_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         varchar(2000) NOT NULL,
    created            timestamp    NOT NULL,
    description        varchar(7000) NOT NULL,
    event_date         timestamp    NOT NULL,
    paid               boolean      NOT NULL,
    participant_limit  integer      NOT NULL,
    published          timestamp,
    request_moderation boolean      NOT NULL,
    state              varchar(20)  NOT NULL,
    title              varchar(120) NOT NULL,
    category_id        bigint       NOT NULL
        constraint fk_cat_id references categories,
    compilation_id     bigint
        constraint fk_comp_id references compilations,
    initiator_id       bigint       NOT NULL
        constraint fk_initiator_id references users,
    location_id        bigint       NOT NULL
        constraint fk_loc_id references locations
);

CREATE TABLE IF NOT EXISTS participation_requests
(
    request_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created           timestamp   NOT NULL,
    status            varchar(20) NOT NULL,
    event_id          bigint      NOT NULL
        constraint fk_event_id references events,
    requester_user_id bigint      NOT NULL
        constraint fk_requester_id references users
);