server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/ewm-stats
    password: pwd
    username: ewm

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

logging:
  level:
    ru:
      practicum:
        ewmstats: trace