--DROP TABLE IF EXISTS statistics;

CREATE TABLE IF NOT EXISTS statistics
(
    request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app        varchar(50)  NOT NULL,
    ip         varchar(15)  NOT NULL,
    timestamp  timestamp    NOT NULL,
    uri        varchar(200) NOT NULL
);